---
- name: virtualbox | Installing Pre-Reqs
  apt:
    name:
      - build-essential
      - "linux-headers-{{ ansible_kernel }}"
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: virtualbox | Installing Pre-Reqs
  yum:
    name:
      - "@Development tools"
      - "kernel-devel-{{ ansible_kernel }}"
      - "kernel-headers-{{ ansible_kernel }}"
      - bzip2
      - dkms
      - gcc
      - make
      - perl
    state: present
  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

- name: virtualbox | Mounting VirtualBox Additions ISO
  mount:
    name: /mnt/virtualbox
    src: "/home/{{ ansible_user }}/VBoxGuestAdditions.iso"
    opts: loop
    state: mounted
    fstype: iso9660
  become: true

- name: virtualbox | Installing VirtualBox Additions
  shell: sh /mnt/virtualbox/VBoxLinuxAdditions.run
  become: true
  failed_when: false

- name: virtualbox | Unmounting VirtualBox Additions ISO
  mount:
    name: /mnt/virtualbox
    state: absent
    fstype: iso9660
  become: true

- name: virtualbox | Removing /home/{{ ansible_user }}/VBoxGuestAdditions.iso
  file:
    path: "/home/{{ ansible_user }}/VBoxGuestAdditions.iso"
    state: absent
  become: true
