---
- name: vmware | Installing open-vm-tools
  package:
    name: open-vm-tools
    state: present
  become: true
  when: not desktop|bool

- name: vmware | Installing open-vm-tools-desktop
  package:
    name: open-vm-tools-desktop
    state: present
  become: true
  when: desktop|bool
