---
name: default-workflow
on: ["push"]
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
