---
name: default-workflow
on: ["push"]
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
